// Extracts a dominant colour for every project from its first screenshot, or
// its logo when it has none, and writes src/data/projectColors.js. Re-run
// after adding or replacing project images:  npm run colors
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import Jimp from 'jimp'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const data = fs.readFileSync(path.join(root, 'src/data/portfolio.js'), 'utf8')
const images = path.join(root, 'public/assets/images')

// Pull (id, first gallery image | logo) out of every project({...}) block.
const blocks = data.split('project({').slice(1)
const entries = blocks.map((b) => {
  const id = b.match(/id: '([^']+)'/)?.[1]
  const gallery = b.match(/gallery: \[img\('([^']+)'\)/)?.[1]
  const logo = b.match(/logo: img\('([^']+)'\)/)?.[1]
  return { id, file: gallery ?? logo, fromLogo: !gallery }
}).filter((e) => e.id && e.file)

const toHsl = (r, g, b) => {
  r /= 255; g /= 255; b /= 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b), l = (max + min) / 2
  if (max === min) return { h: 0, s: 0, l }
  const d = max - min
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
  let h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4
  return { h: h * 60, s, l }
}

async function dominant(file) {
  const img = await Jimp.read(path.join(images, file))
  img.cover(48, 48)
  const buckets = new Map() // hue bucket → { w, r, g, b }
  let fallback = { n: 0, r: 0, g: 0, b: 0 }
  img.scan(0, 0, 48, 48, function (x, y, idx) {
    const [r, g, b, a] = [this.bitmap.data[idx], this.bitmap.data[idx + 1], this.bitmap.data[idx + 2], this.bitmap.data[idx + 3]]
    if (a < 100) return
    fallback = { n: fallback.n + 1, r: fallback.r + r, g: fallback.g + g, b: fallback.b + b }
    const { h, s, l } = toHsl(r, g, b)
    if (s < 0.28 || l < 0.12 || l > 0.88) return // greys, near-black, near-white
    const key = Math.floor(h / 30)
    const w = s * (1 - Math.abs(l - 0.5))
    const cur = buckets.get(key) ?? { w: 0, r: 0, g: 0, b: 0 }
    buckets.set(key, { w: cur.w + w, r: cur.r + r * w, g: cur.g + g * w, b: cur.b + b * w })
  })
  const best = [...buckets.values()].sort((a, b) => b.w - a.w)[0]
  const hex = (r, g, b) => '#' + [r, g, b].map((v) => Math.round(v).toString(16).padStart(2, '0')).join('')
  if (best) return hex(best.r / best.w, best.g / best.w, best.b / best.w)
  if (fallback.n) return hex(fallback.r / fallback.n, fallback.g / fallback.n, fallback.b / fallback.n)
  return null
}

const out = {}
for (const e of entries) {
  try { out[e.id] = await dominant(e.file) } catch (err) { console.warn(`skip ${e.id}: ${err.message}`) }
  console.log(`${e.id.padEnd(20)} ${out[e.id]}  (${e.fromLogo ? 'logo' : 'screenshot'}: ${e.file})`)
}
const js = `// Generated by scripts/project-colors.mjs — dominant colour per project id.\n// Re-run \`npm run colors\` after changing project images.\nexport default ${JSON.stringify(out, null, 2)}\n`
fs.writeFileSync(path.join(root, 'src/data/projectColors.js'), js)
console.log(`\nwrote src/data/projectColors.js (${Object.keys(out).length} projects)`)
